---
title: "Vorticity and Rorquals (vortqual)"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(moveHMM)
library(sf)
library(lubridate)
# Set root directory to project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r data}
load("data/IOS2018_6km_diveDiv.RData")
load("data/IOS2018_6km_VorticityStack.RData")
load("data/IOS2017_6km_diveDiv.RData")
load("data/IOS2017_6km_VorticityStack.RData")
```

Look at the dives
```{r see_dives}
ggplot(diveDiv[!is.na(diveDiv$VatT),], aes(Long, Lat, color = VatT)) +
  geom_point(aes(shape = feed)) +
  geom_path() +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()
```

Bucket by hour
```{r hourly_dives}
hourly_dives <- diveDiv %>%
  group_by(name) %>% 
  mutate(ID = name,
         hour = floor(as.numeric(dttz - min(dttz), units = "hours")),
         depLength = difftime(last(dttz),first(dttz), units = "hours")) %>%# View
  ungroup() %>% 
  filter(depLength > 12) %>% 
  group_by(ID, hour) %>% 
  summarize(lon = mean(Long, na.rm = TRUE),
            lat = mean(Lat, na.rm = TRUE),
            vort = mean(VatT, na.rm = TRUE),
            vortSSD = mean(VorticitySSD, na.rm = TRUE),
            lunges = sum(LungeCount, na.rm = TRUE),
            lungeDepth = mean(meanLungeDepth,na.rm= TRUE)) %>% #View()
  ungroup %>% 
  filter(!is.nan(lon),
         !is.nan(lat)) %>% 
  as.data.frame() %>% 
  mutate(stateLungeIntensity = case_when(lunges == 0 ~ 1,
                                    lunges <= 15 ~ 2,
                                    lunges > 15 ~ 3),
         stateLungeDepth = case_when(is.nan(lungeDepth) ~ 1,
                                lungeDepth <= 50 ~ 2,
                                lungeDepth > 50 ~ 3))
unique(hourly_dives$ID)
LChist <- histogram(hourly_dives$lunges, 
          main = "Distribution of Hourly Lunge Counts",
          breaks = seq(0,100, by = 1),
          xlab = "Lunge Count per Hour", na.rm = TRUE)
LChist



ggplot(hourly_dives, aes(lon, lat, color = vort)) +
  geom_path() +
  geom_point(aes(shape = factor(stateLungeDepth))) +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()
ggplot(hourly_dives, aes(lon, lat, color = vortSSD)) +
  geom_path() +
  geom_point(aes(shape = factor(stateLungeIntensity))) +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()
ggplot(hourly_dives, aes(lon, lat, color = vort)) +
  geom_path() +
  geom_point(aes(shape = factor(stateLungeIntensity))) +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()

```

Fit HMM
```{r fit_hmm}
# Prepare data
dives_prepped <- prepData(hourly_dives, type = "LL", coordNames = c("lon", "lat"))

# Summarize prepared data
summary(dives_prepped)

# Fit HMM

## Lunge Intensity
## Initial parameters (known states are based on # lunges)
step_parsLI <- dives_prepped %>% 
  group_by(stateLungeIntensity) %>% 
  summarize(mu0 = mean(step, na.rm = TRUE),
            sigma0 = sd(step, na.rm = TRUE))

step_par0LI <- c(step_parsLI$mu0, step_parsLI$mu0)
angle_par0LI <- c(c(0, 0, pi), c(1, 1, 1))
## Foraging intensity ~ Vorticity 
dive_hmm_intensity_vort <- fitHMM(dives_prepped,
                        nbStates = 3,
                        stepPar0 = step_par0LI,
                        anglePar0 = angle_par0LI,
                        formula = ~ vort,
                        knownStates = dives_prepped$stateLungeIntensity)
## Foraging intensity ~ VorticitySSD 
dive_hmm_intensity_vortSSD <- fitHMM(dives_prepped,
                        nbStates = 3,
                        stepPar0 = step_par0LI,
                        anglePar0 = angle_par0LI,
                        formula = ~ vortSSD, #+ vort,
                        knownStates = dives_prepped$stateLungeIntensity)


## Lunge Depth 
## Initial parameters (known states are based on # lunges)
step_parsLD <- dives_prepped %>%
  group_by(stateLungeDepth) %>%
  summarize(
            mu0 = mean(step, na.rm = TRUE),
            sigma0 = sd(step, na.rm = TRUE))
#step_parsLD<- add_row(step_parsLD,stateLungeDepth=2,mu0=1,sigma0=1, .before = 3)
step_par0LD <- c(step_parsLD$mu0, step_parsLD$mu0)
angle_par0LD <- c(c(0, 0, pi), c(1, 1, 1))

## Foraging Depth ~ Vorticity 
dive_hmm_depth_vort <- fitHMM(dives_prepped,
                        nbStates = 3,
                        stepPar0 = step_par0LD,
                        anglePar0 = angle_par0LD,
                        formula = ~ vort,
                        knownStates = dives_prepped$stateLungeDepth)


```

Plot HMM
```{r plot_hmm}
#Foraging Intensity ~ Vorticity (0, < 15 Lunges/hr, >15m Lunges/hr)
plot(dive_hmm_intensity_vort, ask = FALSE, plotTracks = TRUE)

#Foraging Intensity ~ VorticitySSD (0, < 15 Lunges/hr, >15m Lunges/hr)
plot(dive_hmm_intensity_vortSSD, ask = FALSE, plotTracks = FALSE)
#Foraging Depth ~ Vorticity (0, < 50m, >50m)
plot(dive_hmm_depth_vort, ask = FALSE, plotTracks = TRUE)

```
