---
title: "Vorticity and Rorquals (vortqual)"
output:
  html_document:
    df_print: paged
---

```{r setup}
library(tidyverse)
library(moveHMM)
library(sf)
# Set root directory to project root
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```

```{r data}
load("data/Bm181021-TDR14_diveDiv.RData")
load("data/Bm181021-TDR14_VorticityStack.RData")
```

Look at the dives
```{r see_dives}
ggplot(diveDiv[!is.na(diveDiv$VatT),], aes(Lon, Lat, color = VatT)) +
  geom_point(aes(size = LungeCount)) +
  geom_path() +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()
```

Bucket by hour
```{r hourly_dives}
hourly_dives <- diveDiv %>% 
  mutate(ID = "bw1",
         hour = floor(as.numeric(dtStart - min(dtStart), units = "hours"))) %>% 
  group_by(ID, hour) %>% 
  summarize(lon = mean(Lon, na.rm = TRUE),
            lat = mean(Lat, na.rm = TRUE),
            vort = mean(VatT, na.rm = TRUE),
            lunges = sum(LungeCount, na.rm = TRUE),
            lungeDepth = mean(meanLungeDepth,na.rm= TRUE)) %>% #View()
  ungroup %>% 
  filter(!is.nan(lon),
         !is.nan(lat)) %>% 
  as.data.frame() %>% 
  mutate(stateLungeIntensity = case_when(lunges == 0 ~ 1,
                                    lunges <= 15 ~ 2,
                                    lunges > 15 ~ 3),
         stateLungeDepth = case_when(is.nan(lungeDepth) ~ 1,
                                lungeDepth <= 50 ~ 2,
                                lungeDepth > 50 ~ 3))

ggplot(hourly_dives, aes(lon, lat, color = vort)) +
  geom_path() +
  geom_point(aes(shape = factor(stateLungeDepth))) +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()
ggplot(hourly_dives, aes(lon, lat, color = vort)) +
  geom_path() +
  geom_point(aes(shape = factor(stateLungeIntensity))) +
  scale_color_gradient2(low = "red", high = "blue") +
  theme_minimal()

```

Fit HMM
```{r fit_hmm}
# Prepare data
dives_prepped <- prepData(hourly_dives, type = "LL", coordNames = c("lon", "lat"))

# Summarize prepared data
summary(dives_prepped)

# Fit HMM
## Initial parameters (known states are based on # lunges)
step_pars <- dives_prepped %>% 
  group_by(stateLungeDepth) %>% 
  summarize(mu0 = mean(step, na.rm = TRUE),
            sigma0 = sd(step, na.rm = TRUE))
step_par0 <- c(step_pars$mu0, step_pars$mu0)
angle_par0 <- c(c(0, 0, pi), c(1, 1, 1))
## Foraging intensity ~ Vorticity 
dive_hmm_intensity_vort <- fitHMM(dives_prepped,
                        nbStates = 3,
                        stepPar0 = step_par0,
                        anglePar0 = angle_par0,
                        formula = ~ vort,
                        knownStates = dives_prepped$stateLungeIntensity)
## Foraging Depth ~ Vorticity 
dive_hmm_depth_vort <- fitHMM(dives_prepped,
                        nbStates = 3,
                        stepPar0 = step_par0,
                        anglePar0 = angle_par0,
                        formula = ~ vort,
                        knownStates = dives_prepped$stateLungeDepth)


```

Plot HMM
```{r plot_hmm}
#Foraging Intensity ~ Vorticity (0, < 15 Lunges/hr, >15m Lunges/hr)
plot(dive_hmm_intensity_vort, ask = FALSE, plotTracks = TRUE)
#Foraging Depth ~ Vorticity (0, < 50m, >50m)
plot(dive_hmm_depth_vort, ask = FALSE, plotTracks = TRUE)

```
